In [32]:
%matplotlib inline
import numpy as np
import pandas as pd



np.random.seed(29)

`1.How likely is it that you roll doubles when rolling two dice?`

In [33]:
rolls = np.random.choice([1, 2, 3, 4, 5, 6], size=(2, 100_000))
rolls

array([[6, 4, 5, ..., 1, 1, 3],
       [4, 4, 6, ..., 5, 6, 5]])

In [34]:
rolls[0].size

100000

In [35]:
#array values : event of rolling two dice.
die1 = rolls[0]
die2 = rolls[1]

In [36]:
print(die1[1])
print(die2[1])

4
4


In [37]:
# vectorize
(die1 == die2).mean()

0.16552

`2. If you flip 8 coins, what is the probability of getting exactly 3 heads?` 
   * What is the probability of getting more than 3 heads?



In [ ]:
# mentally visualize the situation


In [11]:
n_simulations = nrows = 1_000_000
n_trials = ncols = 8
heads = 1
tails = 0
flips = np.random.choice([heads, tails], size=(n_simulations, n_trials))

In [12]:
flips


array([[0, 1, 0, ..., 1, 0, 1],
       [0, 1, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 0, 1, 0],
       ...,
       [1, 0, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 1, 0, 1],
       [1, 1, 0, ..., 1, 0, 1]])

In [14]:
numheads = flips.sum(axis=1)

# average number times the sum equaled 3
calculated_prob = (numheads == 3).mean()


`3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. `
   * Assuming that Codeup randomly selects an alumni to put on a billboard
   * What are the odds that the two billboards I drive past both have data science students on them?

In [41]:
n_simulations = nrows = 1_000_000
n_trials = ncols = 2
data_sci = 1
web_dev = 0
commutes = np.random.choice([data_sci, web_dev], size=(n_simulations, n_trials), p =[0.25, 0.75])

In [ ]:
calculated_prob = 

`4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?`

In [ ]:
# average number of poptarts consumed :
pop_avg = 3

#deviation of poptarts : 1.5
pop_std = 1.5
n_trials = n_cols = 5
n_simulations = n_rows = 1_000_000
sim_consumed_poptarts =np.random

In [ ]:
calculated_prob = (sim_consumed_poptarts.sum(axis=1) < 17).mean()
print(f'The probability...{n_traials} is {})


`5. Compare Heights`
   * Men have an average height of 178 cm and standard deviation of 8cm.
   * Women have a mean of 170, sd = 6cm.
   * __If a man and woman are chosen at random, P(woman taller than man)?__

In [46]:
men_avg = 178
men_std = 8
wmn_avg = 170
wmn_std = 6


In [43]:
s_men = np.random.normal(men_avg, men_std, 1_000_000)
s_men

array([190.7889283 , 180.8992155 , 168.63804163, ..., 169.69179315,
       183.37725036, 177.95322329])

In [44]:
s_men.shape

(1000000,)

In [47]:
s_wmn = np.random.normal(wmn_avg, wmn_std, 1_000_000)

In [ ]:
calculated_prob = (s_wmn > s_man).mean()
print(f'The probability )

`6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. `
   * __What are the odds that after having 50 students download anaconda, no one has an installation issue?__ 
   * __100 students?__
   * __What is the probability that we observe an installation issue within the first 150 students that download anaconda?__

In [52]:
n_simulations = nrows = 1_000_000
#
n_trials = ncols = 50
conda_failure = 1
great_success = 0

#
#
attempted_class_installs = np.random.choice([conda_failure, great_success], size=(n_simulations, n_trials), p = [0.004, 0.996 ])


In [50]:
calculated_prob = 

0.996

In [ ]:
n_simulations = nrows = 1_000_000

n_trials = ncols = 450
conda_failure = 1
great_success = 0


`7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days.`
   *  How unlikely is this?
   *  How likely is it that a food truck will show up sometime this week?
   

In [53]:
n_simulations = nrows = 1_000_000

n_trials = ncols = 3
food_truck = 1
no_truck = 0
lunch_days = np.random.choice([food_truck, no_truck], size=(n_simulations , n_trials), p = [0.7, 0.3])

In [ ]:
calculated_prob = 

In [ ]:
n_simulations = nrows = 1_000_000
n_trials = ncols = 2
food_truck = 1
no_truck = 0

In [ ]:
lunch_days = np.random.choice([food_truck, no_truck], )

`8. If 23 people are in the same room, what are the odds that two of them share a birthday?` 
   * What if it's 20 people?
   * 40?

In [54]:
outcomes= range(0, 365)
#create the data
n_simulations = 1_000_00
n_trials = 23 

In [56]:
classrooms = np.random.choice(outcomes, size=(n_simulations, n_trials))

In [57]:
classrooms

array([[ 21, 124, 349, ..., 290, 240, 172],
       [ 46, 200,   5, ..., 140, 354, 251],
       [253, 197, 102, ..., 141, 145, 193],
       ...,
       [251, 319, 335, ..., 364,  10, 328],
       [ 68, 263, 211, ..., 242, 103, 131],
       [353, 260, 273, ..., 243,  10,  90]])